### PR TITLE
Implement Wiki Enhancements

### PR DESCRIPTION
**Pull request by mmstick**
Implementing the enhancements outlined in the [Wiki](https://github.com/pop-os/gnome-shell-extension-system76-power/wiki).

- [x] Graphics popup menu item descriptions
- [x] Hotplug dialog
- [x] Preparing to switch dialog
- [x] Restart to switch dialog

menu-descriptions
hotplug-dialog
preparing-nvidia
restart-nvidia

### CODE REVIEW

**Comment by mmstick** [comment]
@cassidyjames I've been able to get everything but the spinner implemented so far.

**Comment by cassidyjames** [comment]
@mmstick awesome! There's a little thing with the icon size and text alignment… I know the Shutdown dialog has the secondary text left-aligned with the primary text, and I think the icon is bigger. Is that something we can do for consistency with existing Shell dialogs?

The spinner is probably fine to skip. The only place I can think of for reference would be the app menu loading spinner on the panel, but if we can't do it easily, I think I can find another acceptable icon.

**Comment by cassidyjames** [comment]
shutdown dialog for reference 
screenshot from 2018-06-14 14 19 27

**Comment by mmstick** [comment]
@cassidyjames I can change the alignment.

**Comment by mmstick** [comment]
@cassidyjames How's this?

screenshot from 2018-06-14 14-40-10

**Comment by cassidyjames** [comment]
@mmstick it's hard to tell exactly without getting the ruler out, but that looks really close to me. :+1:

**Comment by cassidyjames** [comment]
@mmstick okay I got out the ruler. Looks like Shell is using 48px icons instead of 64.

**Comment by mmstick** [comment]
@cassidyjames Yeah, using 48px icons here.

**Pull request merged**
